# 🔐 Streamlit Secrets Configuration Template
# 
# COPY THIS FILE TO YOUR STREAMLIT SECRETS SECTION
# Replace all placeholder values with your actual credentials
# 
# ⚠️  WARNING: Never commit this file to Git or share it publicly!

[auth_config]
config = """
credentials:
  usernames:
    admin:
      email: admin@pji-law.com
      name: PJI Law Admin
      password: $2b$12$hashed_password_here
    user1:
      email: user1@pji-law.com
      name: User One
      password: $2b$12$hashed_password_here
    user2:
      email: user2@pji-law.com
      name: User Two
      password: $2b$12$hashed_password_here
cookie:
  name: pji_law_auth
  key: your_super_secret_cookie_key_here
  expiry_days: 30
"""

[gcp_service_account]
type = "service_account"
project_id = "your-google-cloud-project-id"
private_key_id = "your-private-key-id-from-json-file"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC...\n-----END PRIVATE KEY-----\n"
client_email = "your-service-account@your-project.iam.gserviceaccount.com"
client_id = "your-client-id-from-json-file"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/your-service-account%40your-project.iam.gserviceaccount.com"

[google_sheets]
spreadsheet_id = "your-google-sheets-spreadsheet-id"

# Optional: Additional configuration
[app_config]
debug_mode = false
max_upload_size_mb = 50
session_timeout_minutes = 60

# Optional: Email configuration (if you add email features later)
[email_config]
smtp_server = "smtp.gmail.com"
smtp_port = 587
sender_email = "your-email@gmail.com"
sender_password = "your-app-password"
